export const backendData = [
    { id: '01', text: 'Річниця Всеукраїнського референдуму про відділення від СРСР. Рівно 30 років тому  90% українців висловилися за Незалежність України.', url: 'https://w.wiki/8RcL', img: '../public/images/1.jpg' },
    { id: '02', text: 'Ярослав Мудрий у 1015 році посів у Києві княжий престол', url: 'https://www.hroniky.com/news/view/13944-iaroslav-mudryi-u-1015-rotsi-posiv-u-kyievi-kniazhyi-prestol', img: '../public/images/2.jpg' },
    { id: '03', img: '../public/images/3.jpg' },
    { id: '04', img: '../public/images/4.jpg' },
    { id: '05', img: '../public/images/5.jpg' },
    { id: '06', img: '../public/images/6.jpg' },
    { id: '07', img: '../public/images/7.jpg' },
    { id: '08', img: '../public/images/8.jpg' },
    { id: '09', img: '../public/images/9.jpg' },
    { id: '10', img: '../public/images/10.jpg' },
    { id: '11', img: '../public/images/11.jpg' },
    { id: '12', img: '../public/images/12.jpg' },
    { id: '13', img: '../public/images/13.jpg' },
    { id: '14', img: '../public/images/14.jpg' },
    { id: '15', img: '../public/images/15.jpg' },
    { id: '16', img: '../public/images/16.jpg' },
    { id: '17', img: '../public/images/17.jpg' },
    { id: '18', img: '../public/images/18.jpg' },
    { id: '19', img: '../public/images/19.jpg' },
    { id: '20', img: '../public/images/20.jpg' },
    { id: '21', img: '../public/images/21.jpg' },
    { id: '22', img: '../public/images/22.jpg' },
    { id: '23', img: '../public/images/23.jpg' },
    { id: '24', img: '../public/images/24.jpg' },
  ]